### ISSUE TITLE
Add Dark Mauve Theme

### ISSUE THREAD

**Issue by abdulhakim-alshanqiti** [Watt3r/d2-live#1]
I don't know if this is possible or not but it would be nice to have dark mode in links

**Comment by oberwager** [comment]
Hey! Glad to hear you are using this repo.

Looks like dark mode is supported https://d2lang.com/blog/dark-mode/

I can see when I have time to implement this, but PRs are welcome if you want ;)

**Comment by oberwager** [comment]
https://github.com/Watt3r/d2-live/commit/53973ea23a03fc30c996c575cd3d91f77c8e8048 Themes are now supported

**Comment by abdulhakim-alshanqiti** [comment]
Also i think your deploy build failed so you can't currently use themes 

![]  (https://d2.atlas.lucas.tools/?script=cjFSCMhJrEwvyi_NS1HQtVMIzy_KzsxLV3AxUvDMTUxPVfDMU3DMq1TwTSzKTskvz1MISs1LSS1KLVKwUojMLy1ScMxNrAJpCMnPz-ECBAAA__8%3D&theme=200&)

github here uses another link for my pic
![](https://d2.atlas.lucas.tools/?script=cjFSCMhJrEwvyi_NS1HQtVMIzy_KzsxLV3AxUvDMTUxPVfDMU3DMq1TwTSzKTskvz1MISs1LSS1KLVKwUojMLy1ScMxNrAJpCMnPz-ECBAAA__8%3D&theme=200&)
