### ISSUE TITLE
wrong value when using *: {       }

### ISSUE THREAD

**Issue by abdulhakim-alshanqiti** [Watt3r/d2-live#3]
https://play.d2lang.com/?script=4tKyUqjmUlAoLqnMSdVLy88r0S3OrEq1UjA0MOCq5eKqzOcCBAAA__8%3D&sketch=1&

![](https://d2.atlas.lucas.tools/?script=4tKyUqjmUlAoLqnMSdVLy88r0S3OrEq1UjA0MOCq5eKqzOcCBAAA__8%3D&sketch=1&)

for testing >>
https://d2.atlas.lucas.tools/?script=4tKyUqjmUlAoLqnMSdVLy88r0S3OrEq1UjA0MOCq5eKqzOcCBAAA__8%3D&sketch=1&

it should be a bigger text not a new element

**Comment by oberwager** [comment]
Yeah this package hasn't been updated in a while. Should just be a matter of upgrading the go.mod and then everything should be good.

**Comment by abdulhakim-alshanqiti** [comment]
thank you for making this package i am just helping out in what i could

**Comment by oberwager** [comment]
Trying to upgrade it and I'm getting an error on d2lib's side. Opened an issue https://github.com/terrastruct/d2/issues/2004

**Comment by oberwager** [comment]
This should be fixed now

**Comment by abdulhakim-alshanqiti** [comment]
![](https://d2.atlas.lucas.tools/?script=4tKyUqjmUlAoLqnMSdVLy88r0S3OrEq1UjA0MOCq5eKqzOcCBAAA__8%3D&sketch=1&.)


yes its working! the weird thing is github saved the image to the link so everytime the same link is used in github the first time it was used will have the same value


i tried the link i posted above but it had the same value i added a dot at the end of the link to make it a "new" link
